<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<EnableDefaultItems>false</EnableDefaultItems>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<RootNamespace>Plugin1WebApiControllers</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="Controller1.cs" />
	</ItemGroup>	

	<!--OROptimizer.Shared-->
	<ItemGroup Condition="'$(Configuration)'=='Release' Or !$(DefineConstants.Contains('REFERENCE_OROptimizer_Shared_PROJECT'))">
		<PackageReference Include="OROptimizer.Shared" Version="2.7.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug' And $(DefineConstants.Contains('REFERENCE_OROptimizer_Shared_PROJECT'))">
		<ProjectReference Include="..\..\OROptimizer.Shared\OROptimizer.Shared\OROptimizer.Shared.csproj" />
	</ItemGroup>
</Project>
