using IoC.Configuration.Tests.ProxyService.Services;
using IoC.Configuration.Tests.TestTemplateFiles;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace IoC.Configuration.Tests.ProxyService
{
    public class ProxyServiceSuccessfulLoadTests : IoCConfigurationTestsForSuccessfullLoad
    {
        // Set UseOverviewConfigurationFile to true, to test that auto-generated services are properly
        // setup in overview configuration file.
        private static bool UseOverviewConfigurationFile = false;

        protected readonly static string ProxyServiceConfigurationRelativePath =
            UseOverviewConfigurationFile ? "IoCConfiguration_Overview.xml" : "IoCConfiguration_proxyService.xml";

        [TestMethod]
        public void ProxyServiceResolutionTests()
        {
            // IInterface1 is bound to the same type as IInterface1_Extension
            Assert.AreSame(DiContainer.Resolve<IInterface1>(), DiContainer.Resolve<IInterface1_Extension>());

            var interface1User = DiContainer.Resolve<Interface1User>();

            Assert.AreSame(interface1User.Interface1Property, DiContainer.Resolve<IInterface1>());
            Assert.AreSame(interface1User.Interface1Property, DiContainer.Resolve<IInterface1_Extension>());
        }

        [TestMethod]
        public void ProxyServiceResolutionTests_Collections()
        {
            var listOfInt = DiContainer.Resolve<List<int>>();
            Assert.AreEqual(3, listOfInt.Count);
            Assert.AreEqual(19, listOfInt[0]);
            Assert.AreEqual(2, listOfInt[1]);
            Assert.AreEqual(17, listOfInt[2]);
            
            Assert.AreSame(listOfInt, DiContainer.Resolve<IEnumerable<int>>());
            Assert.AreSame(listOfInt, DiContainer.Resolve<IReadOnlyList<int>>());
            Assert.AreSame(listOfInt, DiContainer.Resolve<IList<int>>());

            Assert.AreSame(DiContainer.Resolve<IInterface1>(), DiContainer.Resolve<IInterface1_Extension>());

            var interface1User = DiContainer.Resolve<Interface1User>();

            Assert.AreSame(interface1User.Interface1Property, DiContainer.Resolve<IInterface1>());
            Assert.AreSame(interface1User.Interface1Property, DiContainer.Resolve<IInterface1_Extension>());
        }

        [TestMethod]
        public void AutogeneratedProxyServiceResolutionTests()
        {
            // IAppManager and IAppManager2 are bound to the same type as IAppManager_Extension
            Assert.AreSame(DiContainer.Resolve<IAppManager_Extension>(), DiContainer.Resolve<IAppManager>());
            Assert.AreSame(DiContainer.Resolve<IAppManager_Extension>(), DiContainer.Resolve<IAppManager2>());

            var appManagerUser = DiContainer.Resolve<AppManagerUser>();
            Assert.AreSame(appManagerUser.AppManager, DiContainer.Resolve<IAppManager_Extension>());
            Assert.AreSame(appManagerUser.AppManager, DiContainer.Resolve<IAppManager>());

            var appManager2User = DiContainer.Resolve<AppManager2User>();
            Assert.AreSame(appManager2User.AppManager2, DiContainer.Resolve<IAppManager_Extension>());
            Assert.AreSame(appManager2User.AppManager2, DiContainer.Resolve<IAppManager2>());
        }

        [TestMethod]
        public void PluginProxyServiceResolutionTests()
        {
            Assert.AreSame(
                DiContainer.Resolve(Helpers.GetType("TestPluginAssembly1.Interfaces.IDemoProxyService_Extension")),
                 DiContainer.Resolve(Helpers.GetType("TestPluginAssembly1.Interfaces.IDemoProxyService")));

            Assert.IsInstanceOfType(DiContainer.Resolve(Helpers.GetType("TestPluginAssembly1.Interfaces.IDemoProxyService")),
                Helpers.GetType("TestPluginAssembly1.Implementations.DemoProxyService_Extension_Impl"));
        }
    }
}