<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageVersion>1.0.1</PackageVersion>
        <Version>1.0.1</Version>
        <Authors>OROptimizer</Authors>
        <PackageReadmeFile>README.md</PackageReadmeFile>

		<Title>IoC.Configuration.Maui</Title>

		<Description>
			An IoC.Configuration extension library with Maui integration interface implementations and helper methods.
			Detailed documentation on IoC.Configuration is available at http://iocconfiguration.readthedocs.io/
			Look at http://iocconfiguration.readthedocs.io/
		</Description>

		<Copyright>Copyright 2025 (c) OROptimizer. All rights reserved.</Copyright>
		<PackageTags>IoC Configuration dependencyinjection MAUI inversion of control autofac ninject xml</PackageTags>
		<PackageProjectUrl>http://iocconfiguration.readthedocs.io</PackageProjectUrl>
		<RepositoryUrl>https://github.com/artakhak/IoC.Configuration</RepositoryUrl>

		<PackageReleaseNotes>
			- Referencing latest version of IoC.Configuration
			- Couple of minor changes in project file
		</PackageReleaseNotes>
		
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Maui.Core" Version="8.0.100" />
	</ItemGroup>	

	<!--IoC.Configuration-->
	<ItemGroup Condition="'$(Configuration)'=='Release' Or !$(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
		<PackageReference Include="IoC.Configuration" Version="3.1.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug' And $(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
		<ProjectReference Include="..\IoC.Configuration\IoC.Configuration.csproj" />
	</ItemGroup>

</Project>
