<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>IoC.Configuration.AspNet</RootNamespace>
		<AssemblyName>IoC.Configuration.AspNet</AssemblyName>
		<PackageVersion>1.1.1</PackageVersion>
		<Version>1.1.1</Version>
		<EnableDefaultItems>true</EnableDefaultItems>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Authors>Artak Hakobyan</Authors>
		<Company>OROptimizer</Company>
		<Description>
			An IoC.Configuration extension library with ASP.NET integration interface implementations and helper methods.
			Detailed documentation on IoC.Configuration is available at http://iocconfiguration.readthedocs.io/
			Look at http://iocconfiguration.readthedocs.io/
		</Description>
		<Copyright>Copyright 2025 (c) OROptimizer. All rights reserved.</Copyright>
		<PackageTags>IoC Configuration dependencyinjection ASP.NET inversion of control autofac ninject xml</PackageTags>
		<PackageProjectUrl>http://iocconfiguration.readthedocs.io</PackageProjectUrl>
		<RepositoryUrl>https://github.com/artakhak/IoC.Configuration</RepositoryUrl>
		
		<PackageReleaseNotes>
			- Referencing IoC.Configuration 3.2.0
		</PackageReleaseNotes>
		
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Title>IoC.Configuration.AspNet</Title>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="..\IoC.Configuration.licenseheader" Link="IoC.Configuration.licenseheader" />
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>	

	<!--IoC.Configuration-->
	<ItemGroup Condition="'$(Configuration)'=='Release' Or !$(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
		<PackageReference Include="IoC.Configuration" Version="3.2.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug' And $(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
		<ProjectReference Include="..\IoC.Configuration\IoC.Configuration.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
