<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <RootNamespace>WinUI3Demo</RootNamespace>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <Platforms>x86;x64;ARM64</Platforms>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
        <PublishProfile>win-$(Platform).pubxml</PublishProfile>
        <UseWinUI>true</UseWinUI>
        <EnableMsixTooling>true</EnableMsixTooling>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Assets\SplashScreen.scale-200.png"/>
        <Content Include="Assets\LockScreenLogo.scale-200.png"/>
        <Content Include="Assets\Square150x150Logo.scale-200.png"/>
        <Content Include="Assets\Square44x44Logo.scale-200.png"/>
        <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png"/>
        <Content Include="Assets\StoreLogo.png"/>
        <Content Include="Assets\Wide310x150Logo.scale-200.png"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240428000"/>
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756"/>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0"/>
        <Manifest Include="$(ApplicationManifest)"/>
    </ItemGroup>

    <!--
      Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
      Tools extension to be activated for this project even if the Windows App SDK Nuget
      package has not yet been restored.
    -->
    <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
        <ProjectCapability Include="Msix"/>
    </ItemGroup>

    <!--IoC.Configuration-->
    <ItemGroup Condition="'$(Configuration)'=='Release' Or !$(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
        <PackageReference Include="IoC.Configuration" Version="3.2.0"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)'=='Debug' And $(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
        <ProjectReference Include="..\..\..\IoC.Configuration\IoC.Configuration.csproj"/>
    </ItemGroup>

    <ItemGroup>       
        <ProjectReference Include="..\WinUI3Demo.Interfaces\WinUI3Demo.Interfaces.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\Settings.Designer.cs">
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <None Update="IoCConfiguration.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
    </ItemGroup>

    <!--
      Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
      Explorer "Package and Publish" context menu entry to be enabled for this project even if
      the Windows App SDK Nuget package has not yet been restored.
    -->
    <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
        <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
        <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
        <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
        <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
        <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
        <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
        <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>
