REM Example of calling in command line:
REM k:
REM cd "K:\Projects\OROptimizer\MyGitHubProjects\IoC.Configuration\ApplicationIntegrationDemos\ASP.NET.WebApi\SetupScripts"
REM CopyFiles.bat Debug K:\Projects\OROptimizer\MyGitHubProjects\IoC.Configuration\

REM ConfigurationName is either Debug or Release

SET ConfigurationName=%1
SET SolutionDir=%2

SET "NugetPackagesDir=%USERPROFILE%\.nuget\packages"
SET "IoCConfigurationFiles=%SolutionDir%ApplicationIntegrationDemos\ASP.NET.WebApi\WebApiDemo\IoCConfigurationFiles"
SET "DynamicallyLoadedDlls=%IoCConfigurationFiles%\DynamicallyLoadedDlls"
SET "PluginDlls=%IoCConfigurationFiles%\PluginDlls"
SET "ThirdPartyLibsDir=%IoCConfigurationFiles%\ThirdPartyLibs"
SET "AutogeneratedDlls=%IoCConfigurationFiles%\AutogeneratedDlls\IoCConfiguration"

REM Create test folders
if not exist "%IoCConfigurationFiles%" mkdir "%IoCConfigurationFiles%"
if not exist "%DynamicallyLoadedDlls%" mkdir "%DynamicallyLoadedDlls%"
if not exist "%PluginDlls%" mkdir "%PluginDlls%"
if not exist "%ThirdPartyLibsDir%" mkdir "%ThirdPartyLibsDir%"
if not exist "%AutogeneratedDlls%" mkdir "%AutogeneratedDlls%"

REM Copy third party libraries
xcopy "%NugetPackagesDir%\ninject\3.3.6\lib\netstandard2.0\Ninject.*" "%ThirdPartyLibsDir%" /Y
xcopy "%NugetPackagesDir%\autofac\8.0.0\lib\netstandard2.0\Autofac.*" "%ThirdPartyLibsDir%" /Y
xcopy "%NugetPackagesDir%\autofac.extensions.dependencyinjection\8.0.0\lib\netstandard2.0\Autofac.Extensions.DependencyInjection.*" "%ThirdPartyLibsDir%" /Y

REM Copy IoC extensions

if not exist "%IoCConfigurationFiles%\ContainerImplementations" mkdir "%IoCConfigurationFiles%\ContainerImplementations"
if not exist "%IoCConfigurationFiles%\ContainerImplementations\Autofac" mkdir "%IoCConfigurationFiles%\ContainerImplementations\Autofac"
if not exist "%IoCConfigurationFiles%\ContainerImplementations\Ninject" mkdir "%IoCConfigurationFiles%\ContainerImplementations\Ninject"

REM Enable the code that copies from %NugetPackagesDir% to copy the IoC.Configuration.Autofac and IoC.Configuration.Ninject packages from Nuget
xcopy "%NugetPackagesDir%\ioc.configuration.autofac\2.2.0\lib\netstandard2.0\IoC.Configuration.Autofac.*"  %IoCConfigurationFiles%\ContainerImplementations\Autofac /Y
xcopy "%NugetPackagesDir%\ioc.configuration.ninject\2.2.1\lib\netstandard2.0\IoC.Configuration.Ninject.*"  %IoCConfigurationFiles%\ContainerImplementations\Ninject /Y

REM Enable the code that copies from "%IoCConfigurationFiles%\ContainerImplementations" to copy the IoC.Configuration.Autofac and IoC.Configuration.Ninject packages built by solution
REM xcopy "%SolutionDir%IoC.Configuration.Autofac\bin\%ConfigurationName%\IoC.Configuration.Autofac.*"  "%IoCConfigurationFiles%\ContainerImplementations\Autofac" /Y
REM xcopy "%SolutionDir%IoC.Configuration.Ninject\bin\%ConfigurationName%\IoC.Configuration.Ninject.*"  "%IoCConfigurationFiles%\ContainerImplementations\Ninject" /Y

REM copy DynamicallyLoadedDlls
xcopy "%SolutionDir%ApplicationIntegrationDemos\ASP.NET.WebApi\WebApiDemo.DynamicallyLoadedControllers\bin\Debug\net8.0\WebApiDemo.DynamicallyLoadedControllers.*"  "%DynamicallyLoadedDlls%" /Y

REM copy plugin DLLs
if not exist "%PluginDlls%\WebApiDemoExtension" mkdir "%PluginDlls%\WebApiDemoExtension"

xcopy "%SolutionDir%ApplicationIntegrationDemos\ASP.NET.WebApi\WebApiDemo.Extension\bin\Debug\net8.0\WebApiDemo.Extension.*"  "%PluginDlls%\WebApiDemoExtension" /Y
