using System;
using System.IO;
using IoC.Configuration.ConfigurationFile;
using IoC.Configuration.DiContainer;
using OROptimizer.DynamicCode;

namespace IoC.Configuration.Tests.DocumentationTests.ReferencesInDynamicAssembly;

public class CustomAutoServiceCodeGeneratorDemo : ICustomAutoServiceCodeGenerator
{
    public void GenerateCSharp(ICustomAutoGeneratedServiceInfo customAutoGeneratedServiceInfo, 
        IDynamicAssemblyBuilder dynamicAssemblyBuilder, 
        string generatedClassNamespace, string generatedClassName)
    {
        dynamicAssemblyBuilder.AddReferencedAssembly(
            Path.Combine(Helpers.GetTestFilesFolderPath(), 
                @"DynamicallyLoadedDlls\TestProjects.DynamicallyLoadedAssembly1.dll"));
        
        dynamicAssemblyBuilder.AddReferencedAssembly(
            typeof(SharedServices.Interfaces.IInterface1));

        var classInfo = dynamicAssemblyBuilder.StartDynamicallyGeneratedClass(
            generatedClassName, generatedClassNamespace);
        
        var methodInfo = classInfo.StartMethod("GetValue", typeof(int), 
            Array.Empty<IMethodParameterInfo>(),
            AccessLevel.Public, false, false);
        
        methodInfo.AddCodeLine("=> 10;");
    }
    
    public void Validate(ICustomAutoGeneratedServiceInfo customAutoGeneratedServiceInfo)
    {
       
    }
    
    public void ValidateOnIoCContainerLoaded(IDiContainer diContainer, 
        ICustomAutoGeneratedServiceInfo customAutoGeneratedServiceInfo)
    {
        
    }
}