//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(("K:\\Projects\\OROptimizer\\MyGitHubProjects\\IoC.Configuration\\ApplicationIntegration" +
            "Demos\\Maui\\MauiDemo\\IoCConfiguration.xml"))]
        public string IoCConfigurationFilePath {
            get {
                return ((string)(this["IoCConfigurationFilePath"]));
            }
            set {
                this["IoCConfigurationFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(("K:\\Projects\\OROptimizer\\MyGitHubProjects\\IoC.Configuration\\ApplicationIntegration" +
            "Demos\\Maui\\MauiDemo\\bin"))]
        public string IoCConfigurationDllsPath {
            get {
                return ((string)(this["IoCConfigurationDllsPath"]));
            }
            set {
                this["IoCConfigurationDllsPath"] = value;
            }
        }
    }
}
