using IoC.Configuration.ConfigurationFile;
using IoC.Configuration.DiContainer;
using OROptimizer;
using OROptimizer.DynamicCode;
using System.Collections.Generic;
using System.Linq;

namespace IoC.Configuration.Tests.AssemblyReferencesInDynamicallyGeneratedAssembly;

// This class is used in configuration file.
// ReSharper disable once ClassNeverInstantiated.Global
public class CustomAutoServiceCodeGenerator : ICustomAutoServiceCodeGenerator
{
    /// <summary>
    /// Used in tests to add assemblies that need to be referenced using
    /// <see cref="IDynamicAssemblyBuilder.AddReferencedAssembly(string)"/> in
    /// <see cref="GenerateCSharp(ICustomAutoGeneratedServiceInfo, IDynamicAssemblyBuilder, string, string)"/>
    /// </summary>
    public static List<string> ReferencedAssemblyPathsToAddOnCodeGeneration { get; } = new List<string>();

    public void Validate(ICustomAutoGeneratedServiceInfo customAutoGeneratedServiceInfo)
    {

    }

    public void ValidateOnIoCContainerLoaded(IDiContainer diContainer, ICustomAutoGeneratedServiceInfo customAutoGeneratedServiceInfo)
    {

    }

    public void GenerateCSharp(ICustomAutoGeneratedServiceInfo customAutoGeneratedServiceInfo, IDynamicAssemblyBuilder dynamicAssemblyBuilder, string generatedClassNamespace, string generatedClassName)
    {
        var dynamicClass = dynamicAssemblyBuilder.StartDynamicallyGeneratedClass(generatedClassName,
            new[]
            {
                customAutoGeneratedServiceInfo.ImplementedInterface.GetTypeNameInCSharpClass()
            },
            generatedClassNamespace);

        foreach (var referencedAssemblyPath in ReferencedAssemblyPathsToAddOnCodeGeneration)
            dynamicAssemblyBuilder.AddReferencedAssembly(referencedAssemblyPath);

        var methodInfo = customAutoGeneratedServiceInfo.ImplementedInterface.GetMethods()
            .First(x => x.Name == nameof(IDogWeightsCalculator.GetDogWeightInKilograms));

        var methodData = dynamicClass.StartInterfaceImplementationMethod(methodInfo, false);
        methodData.AddCodeLine("=> (int)(0.453592 * (new DynamicallyLoadedAssembly1.Dog(40)).Weight);");
    }
}