<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!--IoC.Configuration-->
    <ItemGroup Condition="'$(Configuration)'=='Release' Or !$(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
        <PackageReference Include="IoC.Configuration" Version="3.2.0"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)'=='Debug' And $(DefineConstants.Contains('REFERENCE_IoC_Configuration_PROJECT'))">
        <ProjectReference Include="..\..\..\IoC.Configuration\IoC.Configuration.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\WinUI3Demo.Interfaces\WinUI3Demo.Interfaces.csproj"/>
    </ItemGroup>
</Project>
