using System.Xml;
using JetBrains.Annotations;

namespace IoC.Configuration.ConfigurationFile
{
    public class DependencyInjection : ConfigurationFileElementAbstr, IDependencyInjection
    {
        #region  Constructors

        public DependencyInjection([NotNull] XmlElement xmlElement, [NotNull] IConfigurationFileElement parent) : base(xmlElement, parent)
        {
        }

        #endregion

        #region IDependencyInjection Interface Implementation

        public override void AddChild(IConfigurationFileElement child)
        {
            base.AddChild(child);

            if (child is IModulesElement)
                Modules = (IModulesElement) child;
            else if (child is IServices)
                Services = (IServices) child;
            else if (child is IAutoGeneratedServices)
                AutoGeneratedServices = (IAutoGeneratedServices) child;
        }

        public IAutoGeneratedServices AutoGeneratedServices { get; private set; }

        public IModulesElement Modules { get; private set; }
        public IServices Services { get; private set; }

        #endregion
    }
}