// This software is part of the IoC.Configuration library
// Copyright © 2018 IoC.Configuration Contributors
// http://oroptimizer.com
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

using System.Collections.Generic;
using System.Reflection;
using JetBrains.Annotations;

namespace IoC.Configuration.ConfigurationFile
{
    public interface IAutoGeneratedServiceElement : IAutoGeneratedServiceElementBase
    {
        #region Current Type Interface
        /// <summary>
        ///     If the property is implemented in configuration file, returns <see cref="IAutoGeneratedServicePropertyElement" />
        ///     for the implemented property.
        ///     Otherwise, if there is a similar auto-implemented property in configuration file (probably a property that
        ///     belongs to one of the interfaces of auto-implemented interface, which has a compatible return type),
        ///     returns <see cref="IAutoGeneratedServicePropertyElement" /> for that implementation.
        ///     Otherwise, returns null.
        /// </summary>
        /// <param name="propertyInfo">The property information.</param>
        [CanBeNull]
        IAutoGeneratedServicePropertyElement GetAutoGeneratedServicePropertyElement([NotNull] PropertyInfo propertyInfo);

        /// <summary>
        ///     If the method is implemented in configuration file, returns <see cref="IAutoGeneratedServiceMethodElement" />
        ///     for the implemented method.
        ///     Otherwise, if there is a similar auto-implemented method in configuration file (probably a method that
        ///     belongs to one of the interfaces of auto-implemented interface, which has the same signature, and a compatible
        ///     return type),
        ///     returns <see cref="IAutoGeneratedServiceMethodElement" /> for that implementation.
        ///     Otherwise, returns null.
        /// </summary>
        [CanBeNull]
        IAutoGeneratedServiceMethodElement GetAutoGeneratedServicePropertyElement([NotNull] MethodInfo methodInfo);

        [NotNull]
        [ItemNotNull]
        IReadOnlyList<IAutoGeneratedServiceMethodElement> Methods { get; }

        [NotNull]
        [ItemNotNull]
        IReadOnlyList<IAutoGeneratedServicePropertyElement> Properties { get; }

        #endregion
    }
}