using System.Collections.Generic;

namespace IoC.Configuration.ConfigurationFile
{
    public interface IAutoGeneratedServices
    {
        #region Current Type Interface

        IEnumerable<ITypeFactory> TypeFactories { get; }

        #endregion
    }
}