namespace IoC.Configuration.ConfigurationFile
{
    public interface IDependencyInjection : IConfigurationFileElement
    {
        #region Current Type Interface

        IAutoGeneratedServices AutoGeneratedServices { get; }
        IModulesElement Modules { get; }
        IServices Services { get; }

        #endregion
    }
}