using IoC.Configuration.Tests.TestTemplateFiles;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Xml;
using IoC.Configuration.ConfigurationFile;
using IoC.Configuration.Tests.ClassMember.Services;
using TestsSharedLibrary.DependencyInjection;

namespace IoC.Configuration.Tests.ClassMember
{
    [TestClass]
    public class ClassMemberFailedLoadTests : IoCConfigurationTestsBase
    {
        private void LoadConfigurationFile(DiImplementationType diImplementationType,
                                           Action<XmlDocument> modifyConfigurationFileOnLoad)
        {
            base.LoadConfigurationFile(diImplementationType, (container, configuration) => { }, null, modifyConfigurationFileOnLoad);
        }

        protected override string GetConfigurationRelativePath()
        {
            return "IoCConfiguration_classMember.xml";
        }

        [DataTestMethod]
        [DataRow(DiImplementationType.Autofac)]
        [DataRow(DiImplementationType.Ninject)]
        public void ClassDoesNotExist_ClassMemberElementTest(DiImplementationType diImplementationType)
        {
            Helpers.TestExpectedConfigurationParseException(() =>

                LoadConfigurationFile(diImplementationType, (xmlDocument) =>
                {
                    xmlDocument.SelectElement("/iocConfiguration/dependencyInjection/services/service",
                                                    (xmlElement) =>
                                                    {
                                                        return xmlElement.GetAttribute(ConfigurationFileAttributeNames.Type) == typeof(int).FullName;
                                                    })
                                                .SelectChildElement("valueImplementation/classMember")
                               .SetAttributeValue(ConfigurationFileAttributeNames.DeclaringClass,
                                   "IoC.Configuration.Tests.ClassMember.Services.IAppIds_Invalid", ConfigurationFileAttributeNames.DeclaringClassRef);
                }), typeof(IClassMemberValueInitializer));
        }

        [DataTestMethod]
        [DataRow(DiImplementationType.Autofac)]
        [DataRow(DiImplementationType.Ninject)]
        public void ClassMemberDoesNotExist_ClassMemberElementTest(DiImplementationType diImplementationType)
        {
            Helpers.TestExpectedConfigurationParseException(() =>

                LoadConfigurationFile(diImplementationType, (xmlDocument) =>
                {
                    xmlDocument.SelectElement("/iocConfiguration/dependencyInjection/services/service",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute(ConfigurationFileAttributeNames.Type) == typeof(int).FullName;
                                   })
                               .SelectChildElement("valueImplementation/classMember")
                               .SetAttributeValue(ConfigurationFileAttributeNames.MemberName, "DefaultAppId_NonExistent");
                }), typeof(IClassMemberValueInitializer));
        }

        [DataTestMethod]
        [DataRow(DiImplementationType.Autofac)]
        [DataRow(DiImplementationType.Ninject)]
        public void ClassMemberDoesNotHaveValidType_ClassMemberElementTest(DiImplementationType diImplementationType)
        {
            Helpers.TestExpectedConfigurationParseException(() =>

                LoadConfigurationFile(diImplementationType, (xmlDocument) =>
                {
                    xmlDocument.SelectElement("/iocConfiguration/dependencyInjection/services/service",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute(ConfigurationFileAttributeNames.Type) == typeof(int).FullName;
                                   })
                               .SelectChildElement("valueImplementation/classMember")
                               .SetAttributeValue(ConfigurationFileAttributeNames.MemberName, nameof(IAppIds.DefaultAppDescription));
                }), typeof(ValueBasedServiceImplementationElement));
        }

        [DataTestMethod]
        [DataRow(DiImplementationType.Autofac)]
        [DataRow(DiImplementationType.Ninject)]
        public void ClassDoesNotExist_ClassMemberPrefix(DiImplementationType diImplementationType)
        {
            Helpers.TestExpectedConfigurationParseException(() =>

                LoadConfigurationFile(diImplementationType, (xmlDocument) =>
                {
                    xmlDocument.SelectElement("/iocConfiguration/dependencyInjection/autoGeneratedServices/autoService",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute(ConfigurationFileAttributeNames.Interface) == typeof(IAppIdToPriority).FullName;
                                   })
                               .SelectChildElement("autoMethod/if",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute("parameter1") == "_classMember:IAppIds.DefaultAppId";
                                   })
                               .SetAttributeValue("parameter1",
                                   "_classMember:IAppIds_Invalid.DefaultAppId");
                }), typeof(IAutoGeneratedMemberReturnValuesIfSelectorElement));
        }

        [DataTestMethod]
        [DataRow(DiImplementationType.Autofac)]
        [DataRow(DiImplementationType.Ninject)]
        public void ClassMemberDoesNotExist_ClassMemberPrefix(DiImplementationType diImplementationType)
        {
            Helpers.TestExpectedConfigurationParseException(() =>

                LoadConfigurationFile(diImplementationType, (xmlDocument) =>
                {
                    xmlDocument.SelectElement("/iocConfiguration/dependencyInjection/autoGeneratedServices/autoService",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute(ConfigurationFileAttributeNames.Interface) == typeof(IAppIdToPriority).FullName;
                                   })
                               .SelectChildElement("autoMethod/if",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute("parameter1") == "_classMember:IAppIds.DefaultAppId";
                                   })
                               .SetAttributeValue("parameter1",
                                   "_classMember:IAppIds.DefaultAppId_Invalid");
                }), typeof(IAutoGeneratedMemberReturnValuesIfSelectorElement));
        }

        [DataTestMethod]
        [DataRow(DiImplementationType.Autofac)]
        [DataRow(DiImplementationType.Ninject)]
        public void ClassMemberDoesNotHaveValidType_ClassMemberPrefix(DiImplementationType diImplementationType)
        {
            Helpers.TestExpectedConfigurationParseException(() =>

                LoadConfigurationFile(diImplementationType, (xmlDocument) =>
                {
                    xmlDocument.SelectElement("/iocConfiguration/dependencyInjection/autoGeneratedServices/autoService",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute(ConfigurationFileAttributeNames.Interface) == typeof(IAppIdToPriority).FullName;
                                   })
                               .SelectChildElement("autoMethod/if",
                                   (xmlElement) =>
                                   {
                                       return xmlElement.GetAttribute("parameter1") == "_classMember:IAppIds.DefaultAppId";
                                   })
                               .SetAttributeValue("parameter1",
                                   "_classMember:IAppIds.DefaultAppDescription");
                }), typeof(IAutoGeneratedMemberReturnValuesIfSelectorElement));
        }
    }
}
